apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Neeran
  description: Neeran Test
  annotations:
    backstage.io/kubernetes-id: neeran-test
  tags:
    - python
    - data
  links:
    - url: https://example.com/user
      title: Examples Users
      icon: user

spec:
  type: service
  lifecycle: experimental
  owner: team-a
  system: artist-engagement-portal
  dependsOn: ['resource:artists-db']
